### ISSUE TITLE
Warning: Argument "is_enabled" is deprecated

### ISSUE THREAD

**Issue by YannisThalgott** [terraform-aws-modules/terraform-aws-eventbridge#105]
## Description

During a terraform application, I receive a warning, an argument is deprecated on the latest version 3.2.0.
The deprecated element is in the "aws_cloudwatch_event_rule" resource, specifically "is_enabled". 

## ⚠️ Modification to be made

According to the documentation, replace :
`is_enabled = lookup(each.value, "enabled", true)`
with :
`state = ENABLED`

## Versions

- Module version **3.2.0** :
- Terraform version: **v1.7.1**
- Vendor version(s): **5.34.0**
Steps to reproduce behavior :

terraform apply

### Screenshot(s) of terminal output

![image](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/assets/96988793/e62e59a3-74f4-4646-98b2-6a1e5fb025a6)

**Comment by antonbabenko** [comment]
Make sure to update the module version. This issue was fixed in #100.
