### ISSUE TITLE
There are examples of using this module to start AWS Batch jobs?

### ISSUE THREAD

**Issue by mdimarino** [terraform-aws-modules/terraform-aws-eventbridge#109]
It will be nice to have an example showing this using AWS Batch Hashicorp module to schedule jobs.

Thanks!

**Comment by antonbabenko** [comment]
There are no examples for AWS Batch integration, but it should be no different from the integrations with other `targets` listed in the `examples/complete`:

https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/d8a8e76dc36b8d0803ab33ec5e813dd0937eed56/examples/complete/main.tf#L68-L139
