### ISSUE TITLE
Argument is deprecated

### ISSUE THREAD

**Issue by iramello** [terraform-aws-modules/terraform-aws-eventbridge#115]
│ Warning: Argument is deprecated
│
│   with module.eventbridge.aws_cloudwatch_event_rule.this["test"],
│   on .terraform/modules/eventbridge/main.tf line 91, in resource "aws_cloudwatch_event_rule" "this":
│   91:   is_enabled          = lookup(each.value, "enabled", null)
│
│ Use "state" instead

- Module version: 3.2.3
- Terraform version:
```
Terraform v1.7.4
on darwin_arm64
+ provider registry.terraform.io/bwoznicki/assert v0.0.1
+ provider registry.terraform.io/datadog/datadog v3.38.0
+ provider registry.terraform.io/hashicorp/aws v5.41.0
+ provider registry.terraform.io/mongodb/mongodbatlas v1.15.3
````

**Comment by magreenbaum** [comment]
State is available to switch to here: https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/87a112caeba0ba6b77a47e0447070ed23ad64979/main.tf#L95

Here is an example: https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/87a112caeba0ba6b77a47e0447070ed23ad64979/examples/complete/main.tf#L52
