### ISSUE TITLE
EventBridge Scheduled Lambda "crons-rule" Naming

### ISSUE THREAD

**Issue by TotalDwarf03** [terraform-aws-modules/terraform-aws-eventbridge#141]
## Is your request related to a problem? Please describe.
I am using the scheduled lambda pattern to create cron rules in EventBridge which trigger a Lambda. I'm running into an issue where I can't name the cron rule created. It just defaults to "crons-rule". Is there a way to change this? 

[Link to Example](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/5a935234c6d7c528ed532e4b9ba7122bfe04dfd1/examples/with-lambda-scheduling/main.tf#L15)

## Describe the solution you'd like.
To be able to add names to crons rules.

## Describe alternatives you've considered.
Defining the EventBridge resources without use of the module.

## Additional context
Here is the example I am using: [Link to Example](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/5a935234c6d7c528ed532e4b9ba7122bfe04dfd1/examples/with-lambda-scheduling/main.tf#L15)

**Comment by antonbabenko** [comment]
Hi @TotalDwarf03 

You can set `append_rule_postfix = false`, and then the name will be taken from the key of that rule (`crons` in this case).

**Comment by antonbabenko** [comment]
Try this:

```hcl
append_rule_postfix = false

rules = {
  "example-cron" = {
    description         = "Trigger for Lambda Function"
    schedule_expression = var.schedule
  }
}
```

**Comment by TotalDwarf03** [comment]
I get the following error:

│ Error: Invalid index
│ 
│   on .terraform/modules/eventbridge/main.tf line 15, in locals:
│   15:       for target in var.targets[index] :
│     ├────────────────
│     │ var.targets is object with 1 attribute "crons"
│ 
│ The given key does not identify an element in this collection value.

I think the key must be called "crons" as that's what's specified in the module

**Comment by TotalDwarf03** [comment]
Disregard my previous statement, I fixed it. Thank you for your help.

For your references, I had to change both the rules and targets definition to contain "example-crons" instead of "crons".

Example:

```hcl
append_rule_postfix = false

  rules = {
    "example-crons" = {
      description         = "Trigger for Lambda Function"
      schedule_expression = var.schedule
    }
  }

  targets = {
    "example-crons" = [
      {
        name  = "function-cron"
        arn   = aws_lambda_function.lambda_function.arn
        input = jsonencode({})
      }
    ]
  }
```

Thank you @antonbabenko for the help and quick replies 👍

**Comment by antonbabenko** [comment]
I am glad that it works.

Here is a similar example - https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/master/examples/complete/main.tf#L38
