### ISSUE TITLE
Wrong sqs permissions

### ISSUE THREAD

**Issue by rogueturnip** [terraform-aws-modules/terraform-aws-eventbridge#15]
When I create an eventbridge with a target being an SQS queue it ends up create a policy with the wrong sqs action.

```hcl
resource "aws_cloudwatch_log_group" "mybus" {
  name = "/aws/events/my-bus"

  tags = {
    Environment = "production"
    Application = "service"
  }
}

module "eventbridge" {
  source = "terraform-aws-modules/eventbridge/aws"

  bus_name = "my-bus"

  attach_cloudwatch_policy = true
  cloudwatch_target_arns   = [aws_cloudwatch_log_group.mybus.arn]

  attach_sqs_policy = true
  sqs_target_arns = [
    var.event_sqs,
    var.event_sqs_dlq
  ]
}
```

results in a policy of (notice the lowercase sendMessage.

```sh
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "SQSAccess",
            "Effect": "Allow",
            "Action": [
                "sqs:sendMessage*",
                "kms:GenerateDataKey",
                "kms:Decrypt"
            ],
            "Resource": [
                "arn:aws:sqs:us-west-2:xxxx",
                "arn:aws:sqs:us-west-2:xxxx"
            ]
        }
    ]
}
```

**Comment by svenlito** [comment]
Hi @rogueturnip 

Thanks for opening the issue, would you be able to create a PR for this, please?

**Comment by rogueturnip** [comment]
I actually doing have a PR for this, I haven't looked at the module code.  I just made a policy manually and attached it.
 # use this instead of sqs policy since it's generating
  # an invalid policy
  attach_policy_jsons = true
  policy_jsons = [jsonencode(
    {
      "Version" : "2012-10-17",
      "Statement" : [
        {
          "Sid" : "SQSSendMessage",
          "Effect" : "Allow",
          "Action" : [
            "sqs:SendMessage*"
          ],
          "Resource" : [var.event_sqs]
        }
      ]
    })
  ]
  number_of_policy_jsons = 1

**Comment by antonbabenko** [comment]
[v1.7.0](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/releases/v1.7.0) has been just released.
