### ISSUE TITLE
Allow setting AWS IAM role ARN as permission principle 

### ISSUE THREAD

**Issue by LukeEvans** [terraform-aws-modules/terraform-aws-eventbridge#17]
## Is your request related to a new offering from AWS?

Unsure. 

## Is your request related to a problem? Please describe.

Almost certainly a misunderstanding on my part. I seem to be unable to set permissions on my new event bus with a principle set to an existing IAM role.

**My goal is to only allow a single lambda (tied to an IAM role) to `PutEvents` to my event bus with the following:**

```
module "eventbridge" {
  source = "terraform-aws-modules/eventbridge/aws"

  bus_name = "my-bus"
  permissions = {
    "arn:aws:iam::<account>:role/service-role/my-test-role-abc LambdaAccess" = {
      event_bus_name = "my-bus"
    }
  }
  
  tags = {
    Name = "my-bus"
  }
}
```

However this fails with:

```
Error: "principal" must be * or a 12 digit AWS account ID
```

So what I'm trying seems to be fundamentally flawed, but when "managing permissions" in the AWS EventBus console, I am able to manually set the principle to my role's ARN with the following:

```
{
  "Version": "2012-10-17",
  "Statement": [{
    "Sid": "LambdaAccess",
    "Effect": "Allow",
    "Principal": {
      "AWS": "arn:aws:iam::<account>:role/service-role/my-test-role-abc"
    },
    "Action": "events:PutEvents",
    "Resource": "arn:aws:events:us-east-1:<account>:event-bus/my-bus"
  }]
}
```

The above does produce my desired outcome, but I'm unable to mimic this using the terraform module.

## Describe the solution you'd like.
The ability to set the permission principle to a specific AWS IAM role (if possible):

```
  permissions = {
    "arn:aws:iam::<account>:role/service-role/my-test-role-abc LambdaAccess" = {
      event_bus_name = "my-bus"
    }
  }
```

## Describe alternatives you've considered.

I'm confident that there already is another solution to accomplish this and I just can't find it

## Additional context

I'm quite new to terraform, but read the module documentation thoroughly and I'm not clear on how to achieve my desired result. 

If anyone can point me to any documentation I'm missing, I'd be more than happy to close this issue

**Comment by svenlito** [comment]
@LukeEvans Thanks for the issue. We're just passing options through to the Terraform AWS provider, which is where you're getting the error message from. Here are the docs https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_permission

**Comment by LukeEvans** [comment]
Thanks @svenlito - I'll close this issue as user error.
