### ISSUE TITLE
`create_rules = false` causes error

### ISSUE THREAD

**Issue by overflowerror** [terraform-aws-modules/terraform-aws-eventbridge#18]
## Description

`create_rules = false` will always give errors when rules are defined.

## Versions
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.52.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

## Reproduction

- Clone repo
- `cd examples/default-bus`
- Add AWS profile, access_key, secret_key to provider-block
- Add `create_rules = false` to module-block
- `terraform init`
- `terraform plan`

### Code Snippet to Reproduce
```HCL
provider "aws" {
  region = "ap-southeast-1"
  profile="foobar"
  access_key="********"
  secret_key="********"

  # Make it faster by skipping something
  skip_get_ec2_platforms      = true
  skip_metadata_api_check     = true
  skip_region_validation      = true
  skip_credentials_validation = true
  skip_requesting_account_id  = true
}

module "eventbridge" {
  source = "../../"

  create_bus = false
  create_rules = false

  rules = {
    product_create = {
      description   = "product create rule",
      event_pattern = jsonencode({ "source" : ["product.create"] })
    }
  }

  targets = {
    product_create = [
      {
        arn  = aws_sqs_queue.products.arn
        name = "send-product-to-sqs"
      }
    ]
  }
}

##################
# Extra resources
##################

resource "random_pet" "this" {
  length = 2
}

resource "aws_sqs_queue" "products" {
  name = random_pet.this.id
}
```

## Expected behavior
The rules are ignored. The targets are processed.

## Actual behavior
Error: Invalid index

### Terminal Output Screenshot(s)
![screenshot of terminal](https://user-images.githubusercontent.com/4953645/128343379-0dbadafc-c1a2-482a-9d3e-6e40cfc44cb9.png)

## Additional context
Found the problem while trying to construct EventBridge Lambda triggers with terragrunt.

**Comment by antonbabenko** [comment]
Fixed in #19.

[v1.6.0](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/releases/v1.6.0) has been just released.
