### ISSUE TITLE
Unable to use existing non-default event bus when create_event_bus is false

### ISSUE THREAD

**Issue by rnikoopour** [terraform-aws-modules/terraform-aws-eventbridge#21]
## Is your request related to a new offering from AWS?
N/A

## Is your request related to a problem? Please describe.
If `create_event_bus` is set to `false` one cannot set the `bus_name` to target.  It gets set to `default`
* https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/906db9f7dcc01fb5c269efd65f5762e54aa74f36/main.tf#L35
* https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/906db9f7dcc01fb5c269efd65f5762e54aa74f36/main.tf#L53
* https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/906db9f7dcc01fb5c269efd65f5762e54aa74f36/main.tf#L188 (I think this line of code would need to be updated as well.)

## Describe the solution you'd like.
When `create_event_bus` is set to `false` and `bus_name` is set, use the bus name instead of `default`

## Describe alternatives you've considered.
After reading through the terraform code, I'm unable to identify an alternative path forward.

## Additional context
N/A

**Comment by antonbabenko** [comment]
Fixed in #22
