### ISSUE TITLE
Error Inconsistent conditional result types for aws_cloudwatch_event_target

### ISSUE THREAD

**Issue by katariax** [terraform-aws-modules/terraform-aws-eventbridge#23]
## Description

Using the example/complete, ran terraform plan in example/complete directory, and it failed with "Error: Inconsistent conditional result types"

## Versions
 - Terraform: v1.0.5
 - Provider(s): aws 3.54.0
 - Module: terraform-aws-eventbridge

## Reproduction
Using the code from master version as of Aug-19-2021:
- clone repository
- go to example/complete/
- Run terraform init
- Run terraform plan

## Expected behavior
Terraform plan should be successful

## Actual behavior
```
% terraform plan
╷
│ Error: Inconsistent conditional result types
│
│   on ../../main.tf line 49, in resource "aws_cloudwatch_event_target" "this":
│   49:   for_each = var.create && var.create_targets ? {
│   50:     for target in local.eventbridge_targets : target.name => target
│   51:   } : {}
│     ├────────────────
│     │ local.eventbridge_targets is tuple with 8 elements
│     │ var.create is true
│     │ var.create_targets is true
│
│ The true and false result expressions must have consistent types. The given expressions are object and object, respectively.

```

## Additional context
Tried with terraform versions 1.0.4 and 0.12.4 and observed same behaviour

**Comment by svenlito** [comment]
closed via #24
