### ISSUE TITLE
Conditional creation fails

### ISSUE THREAD

**Issue by kmmanto** [terraform-aws-modules/terraform-aws-eventbridge#30]
## Description

Setting `create = false` should disable all resource creation but running apply encounters an error.

**Background:**

We are conditionally creating this resource based on the environment (staging|prod).
```
create = "${var.environment}" == "staging" ? true : false
```

## Versions

 - Terraform: v1.0.10

 - Provider(s): 
provider registry.terraform.io/hashicorp/aws v3.65.0
provider registry.terraform.io/hashicorp/external v2.1.0
provider registry.terraform.io/hashicorp/local v2.1.0
provider registry.terraform.io/hashicorp/null v3.1.0

 - Module:
terraform-aws-eventbridge

## Reproduction

Use/create a module based on this:
```
source  = "terraform-aws-modules/eventbridge/aws"
version = "1.13.0"
```
Set `create = false`
Set rules and targets
Run terraform plan

### Code Snippet to Reproduce

```
  source  = "terraform-aws-modules/eventbridge/aws"
  version = "1.13.0"

  create        = "${var.environment}" == "staging" ? true : false
```

## Expected behavior

`terraform plan` will return with no errors and the reporting the non-creation of the above resource.

## Actual behavior

`terraform plan` fails

### Terminal Output Screenshot(s)

```
│   44:   value       = var.create_rules ? { for p in sort(keys(var.rules)) : p => aws_cloudwatch_event_rule.this[p].id } : {}
│     ├────────────────
│     │ aws_cloudwatch_event_rule.this is object with no attributes
│ 
│ The given key does not identify an element in this collection value.
```

![image](https://user-images.githubusercontent.com/44731627/141984018-393b0ff0-9829-4e99-88a5-ff5fa7b1b309.png)

## Additional context

**Workaround:**
To mitigate the error, we'd have to declare this together with `create = false`
```
create_rules  = "${var.environment}" == "staging" ? true : false
```

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.13.4 :tada:
