### ISSUE TITLE
Provider produced inconsistent final plan when creating new targets

### ISSUE THREAD

**Issue by JoelClemence** [terraform-aws-modules/terraform-aws-eventbridge#32]
## Description

We have noticed when we create new event targets that we get the error:

```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.event_bus.aws_cloudwatch_event_target.this["my new target"] to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.ecs_target: block count changed from 1 to 0.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Re-running the apply works however this is not ideal

## Versions

 - Terraform: 0.13.7

 - Provider(s): aws - 3.55.0

 - Module: 1.10.0

## Reproduction

Steps to reproduce the behaviour:
1. Add new target to existing module
2. Run plan (outputting an out file)
3. Apply the plan from the out file

## Expected behavior
New resources to be deployed

## Actual behavior
Fails with the aforementioned error, however running the apply again works

![Screenshot 2021-11-25 at 09 08 36](https://user-images.githubusercontent.com/15887464/143412714-d68184ab-3630-4f5b-8b88-c81672e47f18.png)

**Comment by pie-r** [comment]
same issue here

**Comment by JoelClemence** [comment]
I did find however, this problem disappeared with terraform v1.1+ so may be specific to terraform 0.13

**Comment by isaac-j-miller** [comment]
Is there a fix for this? I am stuck using terraform version 0.13.7 because of company policy.

**Comment by antonbabenko** [comment]
Unfortunately, we won't be able to support old versions like 0.13.x. You can fork this module and make the required changes, or consider upgrading Terraform version to something more recent.
