### ISSUE TITLE
Module should be able to set eventbridge permission contidional

### ISSUE THREAD

**Issue by kirrmann** [terraform-aws-modules/terraform-aws-eventbridge#34]
## Describe the solution you'd like.
Would like to add a Eventbridge permission with a condition for organization ID. Should be quite easy as the module only passing vars for permissions to `cloudwatch_event_permission` TF resource

## Describe alternatives you've considered.
I used TF resource directly https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_permission#organization-access to archive this permission setup as it was not possible with this module.

**Comment by antonbabenko** [comment]
Hi! Please submit a PR to this repo.

**Comment by antonbabenko** [comment]
I've just added an example of IAM policy condition in 1683fcf but it does not resolve this issue.
