### ISSUE TITLE
Request For Tag Enablement

### ISSUE THREAD

**Issue by sandeepgopi** [terraform-aws-modules/terraform-aws-eventbridge#44]
## Description

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

 - Terraform:

 - Provider(s):

 - Module:

## Reproduction

When we began using the repo, we found that one of the resource is yet to be tag enabled. Hence when our internal projects were calling this repo, our custom tags were not being added in AWS. Please can you enable tags for the below.

Resource (In the main.tf file): "aws_cloudwatch_event_target"
Resource name: "this"

Description : Request you to implement a map(string) variable called tags and ensure this is implemented for:
The ''aws_cloudwatch_event_target" resource with 'this' resource name

**Comment by svenlito** [comment]
Hi, @sandeepgopi thanks for opening this issue. The `aws_cloudwatch_event_target` resource only supports tags on the [ecs_target](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target#ecs_target) is that what you're referring to?

**Comment by sandeepgopi** [comment]
> Hi, @sandeepgopi thanks for opening this issue. The `aws_cloudwatch_event_target` resource only supports tags on the [ecs_target](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target#ecs_target) is that what you're referring to?

Hi @svenlito . Hope you are going well. Yes we are using the ecs_target. Hence would like to tag that when using aws_cloudwatch_event_target resource :)

Please can you enable tags on it. Or if you want I can enable and send a Merge request to you :) 

Thank You 


Kind Regards
Sandeep

**Comment by svenlito** [comment]
@sandeepgopi please sent a PR :)

**Comment by sandeepgopi** [comment]
Hi @svenlito . Hope you are doing well. Thank you for your update.
I have raised a PR.
https://github.com/terraform-aws-modules/terraform-aws-eventbridge/pull/51
At your convenience, please can you review and merge :)

**Comment by sandeepgopi** [comment]
> #51 is not relevant, so I have closed it.

Hi @antonbabenko . Hope you are doing well. Tags are possible for the resource aws_cloudwatch_event_target on the https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target#ecs_target
.
Hence please can you review the PR raised.

To confirm this. Please find this in the document link below https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target

Please infrom me if you need to know anything else to review and approve the PR. Thank you

**Comment by sandeepgopi** [comment]
Hi @svenlito  . Hope you are doing well. 
I have raised a PR.
https://github.com/terraform-aws-modules/terraform-aws-eventbridge/pull/51
At your convenience, please can you review and merge :) Thank You
