### ISSUE TITLE
Pass additional parameters to the SageMaker Pipeline

### ISSUE THREAD

**Issue by marko-pejic** [terraform-aws-modules/terraform-aws-eventbridge#53]
## Is your request related to a new offering from AWS?
  - No 🛑

## Is your request related to a problem? Please describe.

- No 🛑

## Describe the solution you'd like.

A complete example in which a EventBridge that starts SageMaker pipeline execution **with additional parameters** is created.

## Describe alternatives you've considered.

Simple example with passing data to the SageMaker pipeline through the EventBridge

**Comment by svenlito** [comment]
@marko-pejic I suppose the examples aren't sufficient enough? https://docs.aws.amazon.com/sagemaker/latest/dg/automating-sagemaker-with-eventbridge.html

**Comment by marko-pejic** [comment]
@svenlito I know how to do that through EventBridge console, that's pretty straight-forward. However, I have a problem how to do this through terraform script using your module, so I need help (working example) with that.
Thanks

**Comment by tachomi** [comment]
@marko-pejic were you able to find a solution? As you said, is not clear how to integrate the execution of Sagemaker Pipeline & EventBridge with terraform, not only in this module, but in a general terraform solution

**Comment by marko-pejic** [comment]
@tachomi I couldn't find a solution for this particular case, there is not a single example where parameters are passed through terraform to the SageMaker pipeline. Can anyone help us with this?
