### ISSUE TITLE
Import of already created EventBridge rules fail due to appending "-rule" in the name of the rule

### ISSUE THREAD

**Issue by AhmadkSalah** [terraform-aws-modules/terraform-aws-eventbridge#57]
### Description:

When Importing an existing rule and trying to apply, terraform shows that the same rule must be destroyed and created again due to the fact that the module appends "-rule" to the name of that rule, so as a solution we forked and modified the module to make the postfix optional first then opening a PR here, 

### Steps to reproduce the issue : 

- Import any already created rule that has no "-rule" at the end of its name 
- Perform the "terraform plan" and check for the changes 

### Versions:

- Terraform Version : **Terraform v1.1.7**
- **provider registry.terraform.io/hashicorp/aws v4.21.0**
- Module Version : **V1.14.1 (Latest)**

### Note:
This issue also applies for EventBridge connections and EventBridge API Destinations, we can confirm this by checking the code however we didn't test as we dont use them 

### Proposed fix:

Create 3 bool variables , by default its true to allow postfix appending, however when false is passed as a value it will not append the postfix

**Comment by haytham-salhi** [comment]
Hi @antonbabenko, we proposed a change for this issue. Can you plz review?

**Comment by AhmadkSalah** [comment]
Issue Fixed in v1.14.2
