### ISSUE TITLE
CloudWatch target needs resource-based permission

### ISSUE THREAD

**Issue by breitsmiley** [terraform-aws-modules/terraform-aws-eventbridge#59]
## Is your request related to a problem? Please describe.
When EventBridge has CloudWatch target - it is not work at all without next resource-based policy for CloudWatch Group:

- [https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-log-group-eventbridge/](https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-log-group-eventbridge/)
- [https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-use-resource-based.html#eb-cloudwatchlogs-permissions](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-use-resource-based.html#eb-cloudwatchlogs-permissions)

```
{
    "Statement": [
        {
            "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Effect": "Allow",
            "Principal": {
                "Service": ["events.amazonaws.com", "delivery.logs.amazonaws.com"]
            },
            "Resource": "arn:aws:logs:region:account:log-group:/aws/events/*:*",
            "Sid": "TrustEventsToStoreLogEvent"
        }
    ],
    "Version": "2012-10-17"
}  
```
Policy above automatically created when adding an EventBridge target via AWS Management Console. 
Should we add creation of this policy by terraform-aws-eventbridge module ?

## Describe the solution you'd like.

Add creation of needed policy by using [aws_cloudwatch_log_resource_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target#cloudwatch-log-group-usage) resource in the module.

## Describe alternatives you've considered.
Managing separately outside of module

**Comment by clalexander** [comment]
I would like this feature.  Took me a while to trace this down...  Based on the module interface, I expected the Cloudwatch log target to work.
