### ISSUE TITLE
AWS provider version contraint should be >= 4.7.0

### ISSUE THREAD

**Issue by aaroneuph** [terraform-aws-modules/terraform-aws-eventbridge#65]
## Description

A recent change added the data source for `aws_cloudwatch_event_bus`.  This data source was introduced in the AWS provider version [v4.7.0](https://newreleases.io/project/github/hashicorp/terraform-provider-aws/release/v4.7.0).  The AWS provider constraint should likely contain a constraint that reflects the new requirement.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

- Provider version(s):

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.17.0 :tada:
