### ISSUE TITLE
Last minor version changes to new major aws provier version

### ISSUE THREAD

**Issue by kaiweingaertner8080** [terraform-aws-modules/terraform-aws-eventbridge#67]
## Description

With version v1.17.0 the required_providers for aws was changed to >=4.7 from >= 3.44. This breaks clients that have a ~> dependency on this module and cannot update to the new aws major version. A minor version change should not update to a new provider major version.

## Expected behavior

1.* versions remain compatible to aws provider 3.*

## Actual behavior

1.17 requires aws provider >= 4.7

**Comment by antonbabenko** [comment]
Right, this should have been a major release.
