### ISSUE TITLE
cannot use "default" bus name

### ISSUE THREAD

**Issue by ashishera** [terraform-aws-modules/terraform-aws-eventbridge#69]
## Description

I'm unable to use "default" as the event bus while trying to create event rule using "eventbridge" module. The "default" bus exists in my aws account and is selectable while creating the event rule manaully through AWS console.

## Versions
- Module : eventbridge
- Module version [Required]: 1.17.0

- Terraform version: 1.3.3
 
- Provider version(s): AWS v.4.39.0

## Reproduction Code [Required]
module "eventbridge" {
  source = "terraform-aws-modules/eventbridge/aws"
  version = "1.17.0"
  bus_name = "default"

  rules = {
    aws-scheduled-events = {
      description   = "scheduled aws events"
      event_pattern = <<PATTERN
      {
        "source": ["aws.health"],
        "detail-type": ["AWS Health Event"],
        "detail": {
          "service": ["EC2"],
          "eventTypeCategory": ["scheduledChange"]
        }
      }
      PATTERN
      enabled       = true
    }
  }

  targets = {
    aws-scheduled = [
            {
        name = "SNS topic"
        arn = module.sns_topic.sns_topic_arn
        
      }
    ]
  }

## Expected behavior

The event rule should be created in the "default" event bus.

## Actual behavior

Below is the error message on the console after  _terraform plan_

module.chatbot.aws_cloudformation_stack.tf_chatbot["Amgen-Nimbus"]: Refreshing state... [id=arn:aws:cloudformation:us-west-2:450285764213:stack/terraform-chatbot-Amgen-Nimbus/22d94af0-65e7-11ed-8468-0aca3ec2da0f]
╷
│ Error: invalid value for name (cannot be 'default')
│
│   with module.eventbridge.aws_cloudwatch_event_bus.this[0],
│   on .terraform/modules/eventbridge/main.tf line 43, in resource "aws_cloudwatch_event_bus" "this":
│   43:   name = var.bus_name
│

**Comment by jamesfmaccoll** [comment]
if you're just using the default bus, don't declare it, it'll just get build by default.
So either moit the line"bus_name = "default" or hash it out #bus_name = "default"

**Comment by ashishera** [comment]
Hi,

I tried both by removing and hashing out #bus_name = "default", but received an error both times. FYI... we already have 'default' event bus and the module should have used it.


module "eventbridge" {
source = "terraform-aws-modules/eventbridge/aws"
version = "1.17.0"

rules = {
aws-scheduled-events = {
description = "scheduled aws events"
event_pattern = <<PATTERN
..
..
.


Error after running terraform plan:

module.eventbridge.data.aws_iam_policy_document.assume_role[0]: Read complete after 0s [id=2423734833]
module.chatbot.aws_iam_role.chatbot[0]: Refreshing state... [id=Amgen-Nimbus-chatbot-role]
module.eventbridge.aws_iam_role.eventbridge[0]: Refreshing state... [id=scheduled_events_bus]
aws_sns_topic_subscription.email_target: Refreshing state... [id=arn:aws:sns:us-west-2:450285764213:aws-scheduled-events-notifications:28377bf8-dc3d-4098-93f0-a4908f8e49c1]
module.chatbot.aws_iam_role_policy_attachment.chatbot_policy[0]: Refreshing state... [id=Amgen-Nimbus-chatbot-role-20221116194450585400000003]
module.chatbot.aws_cloudformation_stack.tf_chatbot["Amgen-Nimbus"]: Refreshing state... [id=arn:aws:cloudformation:us-west-2:450285764213:stack/terraform-chatbot-Amgen-Nimbus/22d94af0-65e7-11ed-8468-0aca3ec2da0f]
╷
│ Error: invalid value for name (cannot be 'default')
│
│   with module.eventbridge.aws_cloudwatch_event_bus.this[0],
│   on .terraform/modules/eventbridge/main.tf line 43, in resource "aws_cloudwatch_event_bus" "this":
│   43:   name = var.bus_name
│
╵

**Comment by donsokolone** [comment]
When using `default` event bus with this module you need to set `create_bus = false`.
