### ISSUE TITLE
Eventbridge Scheduler

### ISSUE THREAD

**Issue by roberto-nascimento** [terraform-aws-modules/terraform-aws-eventbridge#70]
## Is your request related to a new offering from AWS?
Yes, it is a new feature.
https://aws.amazon.com/pt/blogs/compute/introducing-amazon-eventbridge-scheduler/

## Describe the solution you'd like.
- Full suport for new feature, like schedules and schedule groups

**Comment by roberto-nascimento** [comment]
sorry wrong project

**Comment by pmcenery-bl** [comment]
I don't think this is the wrong project. I was about to open an issue after the AWS provider was updated to include a new `aws_scheduler_schedule` resource [1]. The AWS Scheduler is part of Event Bridge. The use case that would like is to be able to specify a timezone in a schedule.

It would be nice to be able to schedule lambda or step functions using this module with these new resources. Please can be discussed. I don't believe there is a dedicated terraform module for this.

References
1. [EventBridge Scheduler](https://github.com/hashicorp/terraform-provider-aws/issues/27760)
