### ISSUE TITLE
AWS Event Bridge - Terraform for Pipes Feature

### ISSUE THREAD

**Issue by kaiqueprazeres** [terraform-aws-modules/terraform-aws-eventbridge#72]
# Description

Hey. After the release of the Event Bridge Pipes feature, we need to know when terraform intents to release the resource/module for this feature.

Do you have a release date?

Thank you for attention.

**Comment by Stocco** [comment]
We need this as well. Please release the terraform for the pipes feature :)

**Comment by antonbabenko** [comment]
This feature is dependent on https://github.com/hashicorp/terraform-provider-aws/issues/28153

**Comment by srodgers-awaze** [comment]
The dependent feature was released in [v5.6.0 of the Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws/blob/v5.6.0/CHANGELOG.md). Could this be re-opened?

**Comment by antonbabenko** [comment]
Fixed in #92
