### ISSUE TITLE
EventBridge with schedule rule and Step Functions target

### ISSUE THREAD

**Issue by yushkevicham** [terraform-aws-modules/terraform-aws-eventbridge#73]
module "eventbridge". version = "1.17.0"
Hey. I want to apply EventBridge with schedule rule and Step Functions target for multiple environments. How can I customize the IAM role name to access state machines? I'm running into a error: error creating IAM Policy default-sfn: EntityAlreadyExists: A policy called default-sfn already exists. Duplicate names are not allowed.

**Comment by kostasns** [comment]
Hello,

you can provide `role_name` variable in module to set desired name for your role
https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/f75a5512af190544ec2a872b385b9c0d541416b9/iam.tf#L8

**Comment by yushkevicham** [comment]
> Hello,
> 
> you can provide `role_name` variable in module to set desired name for your role
> 
> https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/f75a5512af190544ec2a872b385b9c0d541416b9/iam.tf#L8

Thanks, I already figured it out. Initially confused by the description: Name of IAM role to use for **Lambda Function**

**Comment by yushkevicham** [comment]
Let me ask one more question. How can I change the name of an eventbridge rule from a default "crons-rule" to another.  tags = {
    Name = "Bla-bla-bla" } doesn't work.

**Comment by kostasns** [comment]
Use the name "Bla-bla-bla" instead of "crons"
https://github.com/terraform-aws-modules/terraform-aws-eventbridge/blob/f75a5512af190544ec2a872b385b9c0d541416b9/main.tf#L6

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.17.1 :tada:
