### ISSUE TITLE
AWS EventBridge Scheduler Support

### ISSUE THREAD

**Issue by pmcenery-bl** [terraform-aws-modules/terraform-aws-eventbridge#81]
I was hoping that [this issue](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/issues/70) could be re-opened. Failing that, here is a new issue.

Would it be possible to include support for [AWS EventBridge Scheduler](https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/) in this module? A new `aws_scheduler_schedule`[1] resource has already been added to the AWS provider. The use case that I would like is to be able to specify a timezone in a schedule. Please can support for this be added?

References

1. https://github.com/hashicorp/terraform-provider-aws/issues/27760

**Comment by pmcenery-bl** [comment]
Please can this issue be re-opened?

**Comment by antonbabenko** [comment]
@pmcenery-bl All we need is for someone to come up with the PR for this feature.

**Comment by pmcenery-bl** [comment]
@antonbabenko Please seem my PR [here](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/pull/83). Some feedback on the handling of the assume role would be good. I was thinking of having a paramater along the lines of `enable_scheduler` which allows the module to decide whether the assume role trusts `events` (and/or) `scheduler`. At present, I've simply assumed that the trusted entities need to be [expanded upon](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/pull/83/commits/602f10a919351a1a1894e82a3f1682977764b5ae#diff-87e46dba536b3ad6d009a555140c7ec67f022dd3b56a7296ec89b1fd96ea1818R16) to include scheduler. See the example provided [here](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/pull/83/commits/602f10a919351a1a1894e82a3f1682977764b5ae#diff-87e46dba536b3ad6d009a555140c7ec67f022dd3b56a7296ec89b1fd96ea1818R11-R26). Other than that, I've been using and testing it and its working well so far.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.3.0 :tada:
